config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "pages#index"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
     resources :postcomments	
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomments
	validates :title, length: { in: 1..10}
	validates :title, :body, presence: true
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :text, presence: true
	validates :text, format: { with:  /[a-zA-Z_#][\w.!?,&|@#$%^:;'"-]*/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable




  has_many :posts     
  has_many :postcomments  

validates :nickname, :password, :email, presence: true
validates :nickname, length: { in: 6..15 }
validates :nickname, :email, uniqueness: true
validates :nickname, format: { with: /\A[a-zA-Z0-9]+\Z/ }
validates :nickname, format: { without: /\s/ }
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}, default_url: "/images/default.jpeg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :devise_sign_up_params, if: :devise_controller?
  protect_from_forgery with: :exception

  private

  def devise_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys:[:attribute, :nickname ])
     devise_parameter_sanitizer.permit(:sign_up, keys:[:attribute, :avatar])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	pp @users = User.all
  	pp @posts = Post.all
  end
end

app/controllers/postcomments_controller.rb
class PostcommentsController < ApplicationController

before_action :authenticate_user!

def create
	params[:postcomment][:post_id] = params[:post_id]
	params[:postcomment][:user_id] = current_user.id
	@comment = Postcomment.create(postcomments_params)
	if @comment.save
		redirect_to post_path(params[:post_id])
	else 
		@comment.errors.full_messages.each do |msg|  
		@msg = msg
    end  
    flash[:notice] = "#{@msg}"
    redirect_to post_path(params[:post_id])
	end
end

private
def postcomments_params
	params.require(:postcomment).permit(:user_id, :post_id, :text)
	
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show,:edit,:update,:destroy]
  def new
  @post = Post.new
  end 

  def show
    @comments = Postcomment.where(post_id: @post.id)
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end

  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:user_id,:title,:body)
  
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<style>
    footer {
            background-color: black;
        }
        
#justpushtobottom {
    height: 82vh;
}
   
    
</style>


  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <title>Bootstrap 101 Template</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
  
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
</head>
<body>

<div id="justpushtobottom"> 
</div>

<footer class="footer p-t-1">
        <div class="container">
            

           <h3 style="text-align: center;"> <a href="#"><i class="fa fa-facebook-official fa-2x"></i></a>
            <a href="#"><i class="fa fa-pinterest-p fa-2x"></i></a>
            <a href="#"><i class="fa fa-twitter fa-2x"></i></a>
            <a href="#"><i class="fa fa-flickr fa-2x"></i></a>
            <a href="#"><i class="fa fa-linkedin fa-2x"></i></a></h3>

            
        </div>
    </footer>
</body>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Blog", root_path, class: "navbar-brand"%>
  
    </div>
      
    <ul class="nav navbar-nav navbar-right">
    <% if current_user.nil? %>
    <li>
    <%= link_to user_session_path do %>
      <i class="glyphicon glyphicon-user"></i> Login
      <%end%>
      </li>
      <% else %> 
      <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="glyphicon glyphicon-log-in"></i> Logout
  <%end%>
      </li>
       <% end %>
    </ul>

    
      

  </div>  
    
</nav>
 
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
    
  </body>
</html>

app/views/pages/index.html.erb
<%= link_to "Create new post", new_post_path, class: "btn btn-default" %>

<div>
<% @posts.each do |post| %>
<hr>
  <h1><%= link_to post.title, post_path(post.id) %></h1>
  <p><%= image_tag post.user.avatar.url(:thumb), width: 30, height: 30 %></p>
  <p>Author: <%= post.user.nickname %> | 
   Create at: <%= post.created_at %></p>
   <p><%= sanitize post.body %></p>
  <% if current_user != nil and current_user.id == post.user_id %>
  <p>
  <%= link_to "Edit",  edit_post_path(post.id) %> or
  <%= link_to "Delete", post_path(post.id), data: {confirm: 'Rili deleted your post?'}, method: :delete %>
  </p>
  <%end%>
<%end%>
</div>

app/views/posts/_form.html.erb
<p><%= f.label :title %></p>
<%= f.text_field :title %><br />

<p><%= f.label :body%></p>
<%= f.text_area :body, :class => "tinymce", :rows => 40, :cols => 120 %>
<%= tinymce %>

<p><%= f.submit "Save"%></p>

app/views/posts/edit.html.erb
<%= form_for :post, url:post_path, method: :patch do |f| %>
 <% if @post.errors.any?  %>
   <% @post.errors.full_messages.each do |msg| %>
   <li><%= msg%></li>
   <%end%>
   <%end%>

<%= render 'posts/form',f:f %>

<% end %>

app/views/posts/new.html.erb
<%= form_for @post, url: posts_path,validate: true do |f| %>
<% if @post.errors.any? %>
<% @post.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
<% end %>

<%= render 'posts/form', f:f %>


<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title%></h1>
<p><%= sanitize @post.body%></p>

<hr>
<% @comments.each do |comment|%>
<p>User <b><%= comment.user.nickname %></b> write: </p>
<%= comment.text %>
<hr>
<% end %>

<%= form_for :postcomment, url: post_postcomments_path(post_id: @post.id) do |f| %>

<% if flash[:notice] %>
	<div class="notice"> <%= flash[:notice] %> </div>
<% end %>

<p><%= f.label "Write Comment" %></p>
<%= f.text_area :text, cols: 10, rows: 5 %><br />

<p><%= f.submit "Send"%></p>

<%end%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>